version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env  # This should contain your MongoDB Atlas URL like MONGO_URI=mongodb+srv://...
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
